// DO NOT EDIT! This file is automatically generated.
import request from './request';

export type AddBookDto = { name: string; author: string; retailPrice: number };
export type GetBookDto = { id: number | undefined; name: string | undefined };
export type GetStateDto = { id: number | undefined; name: string | undefined };

export default {
  books: {
    create(params: { book: AddBookDto }): Promise<boolean> {
      return request('post', '/books/create', params);
    },
    getBook(params: { id: number }): Promise<{ book: GetBookDto }> {
      return request('get', '/books/get_book', params);
    },
    getBooks(): Promise<{ books: GetBookDto[] }> {
      return request('get', '/books/get_books', {});
    },
    hello(): Promise<{ message: string }> {
      return request('get', '/books/hello', {});
    }
  },
  states: {
    getStates(): Promise<{ states: GetStateDto[] }> {
      return request('get', '/states/get_states', {});
    }
  }
};
